In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
pd.set_option("display.max_columns", None)
sns.set_theme(style = "darkgrid")
warnings.filterwarnings("ignore")

In [3]:
x = pd.read_csv("../data/cleaned_and_split/x.csv")
x_train = pd.read_csv("../data/cleaned_and_split/x_train.csv")
x_test = pd.read_csv("../data/cleaned_and_split/x_test.csv")
y = pd.read_csv("../data/cleaned_and_split/y.csv")
y_train = pd.read_csv("../data/cleaned_and_split/y_train.csv")
y_test = pd.read_csv("../data/cleaned_and_split/y_test.csv")

In [4]:
x.head()

   Unnamed: 0     x     y    z
0           0  0.04  0.02  1.0
1           1  0.04  0.02  1.0
2           2  0.04  0.02  1.0
3           3  0.04  0.02  1.0
4           4  0.04  0.02  1.0

In [5]:
x_train.head()

   Unnamed: 0     x     y    z
0        9318  0.04  0.03  1.0
1       18896  0.04  0.05  1.0
2        8871  0.04  0.02  1.0
3       18790  0.04  0.04  1.0
4       17362  0.04  0.03  1.0

In [6]:
x_test.head()

   Unnamed: 0     x     y     z
0       10178 -0.14  0.06  0.93
1        8585  0.05  0.02  1.03
2         451 -0.01  0.05  1.12
3        6014  0.04  0.03  1.00
4       15342  0.06 -0.05  1.00

In [7]:
y.head()

   Unnamed: 0  gesture_name
0           0             0
1           1             0
2           2             0
3           3             0
4           4             0

In [8]:
y_train.head()

   Unnamed: 0  gesture_name
0        9318             3
1       18896             6
2        8871             3
3       18790             6
4       17362             6

In [9]:
y_test.head()

   Unnamed: 0  gesture_name
0       10178             3
1        8585             3
2         451             0
3        6014             2
4       15342             5

In [10]:
x.drop(columns = ["Unnamed: 0"], inplace = True)
x_train.drop(columns = ["Unnamed: 0"], inplace = True)
x_test.drop(columns = ["Unnamed: 0"], inplace = True)
y.drop(columns = ["Unnamed: 0"], inplace = True)
y_train.drop(columns = ["Unnamed: 0"], inplace = True)
y_test.drop(columns = ["Unnamed: 0"], inplace = True)

In [11]:
x.head()

      x     y    z
0  0.04  0.02  1.0
1  0.04  0.02  1.0
2  0.04  0.02  1.0
3  0.04  0.02  1.0
4  0.04  0.02  1.0

In [12]:
x_train.head()

      x     y    z
0  0.04  0.03  1.0
1  0.04  0.05  1.0
2  0.04  0.02  1.0
3  0.04  0.04  1.0
4  0.04  0.03  1.0

In [13]:
x_test.head()

      x     y     z
0 -0.14  0.06  0.93
1  0.05  0.02  1.03
2 -0.01  0.05  1.12
3  0.04  0.03  1.00
4  0.06 -0.05  1.00

In [14]:
y.head()

   gesture_name
0             0
1             0
2             0
3             0
4             0

In [15]:
y_train.head()

   gesture_name
0             3
1             6
2             3
3             6
4             6

In [16]:
y_test.head()

   gesture_name
0             3
1             3
2             0
3             2
4             5

In [ ]:
# using Sequential API from keras to build a classifier